import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

//Components
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-primary min-h-screen w-screen-xl">
          <main className="max-w-screen-3xl m-auto bg-primary">
            <div className="grid grid-cols-4 lg:grid-cols-12">
              <Header/>
              {children}  
              <Footer/>            
            </div>
          </main>
        </main>
      </body>
    </html >
  );
}
