import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-primary min-h-screen w-screen-xl">
          <main className="max-w-screen-2xl m-auto bg-primary">
            <div className="grid grid-cols-4 lg:grid-cols-12">
              {children}              
            </div>
          </main>
        </main>
      </body>
    </html >
  );
}
